version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - php
      - mysql
    networks:
      - shared

  php:
    build:
      args:
        user: Username
        uid: 1000
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    working_dir: /var/www/
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
      #XDEBUG_CONFIG: remote_host=192.168.122.1
    volumes:
      - ./:/var/www/
      - ./docker/php-ini:/usr/local/etc/php/custom.d
    ports:
      - "9000:9000"
    networks:
      - shared

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - shared
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8086:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
    volumes:
      - ./docker/phpmyadmin:/var/www/phpmyadmin
    networks:
      - shared

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./docker/redis:/data
    ports:
      - "6379:6379"
    networks:
      - shared

networks:
  shared:
    external:
      name: shared
